### ISSUE TITLE
Queue doesn't detect genre/language correctly

### ISSUE THREAD

**Issue by WTHBRO** [Sebola3461/osumodweb#12]
Tried requesting a japanese/electronic map to my own queue, system says "this queue doesn't accept this language" while both are in my accepted list

edit: all of my pending maps dont work it seems

**Comment by RozenLily** [comment]
Had this issue as well but with a Japanese/Rock map. The "this queue doesn't accept this language" thing would appear while I had the language in osu! website set to Japanese. Request went through just fine after changing osu! website language to English.

**Comment by Sebola3461** [comment]
i know this issue, ill try to fix in the next update, sorry...

**Comment by Sebola3461** [comment]
can you try now?

**Comment by WTHBRO** [comment]
works great now, thanks
