### ISSUE TITLE
Fix text wrap on mobile

### ISSUE THREAD

**Issue by Aljotzi** [Sebola3461/osumodweb#15]
On mobile, when words reach the end of a line, instead of moving the entire word to the next line, it breaks the word in half making stuff hard to read sometimes.
![Screenshot_20211220-164719_Chrome](https://user-images.githubusercontent.com/45378469/146852416-41273347-8f65-4e26-89d5-416fd159ab7e.jpg)
![Screenshot_20211220-164601_Chrome](https://user-images.githubusercontent.com/45378469/146852419-ccf96c5e-bd14-430b-9474-b25a6c2b0922.jpg)

**Comment by Sebola3461** [comment]
ill fix in a next release

**Comment by Sebola3461** [comment]
fixed
