### ISSUE TITLE
Desktop notifications doesn't redirect correctly

### ISSUE THREAD

**Issue by gaston2199** [Sebola3461/osumodweb#7]
I did a request to D0UG and I received the notification, but when I click on it, it simply redirects me to the wrong page 

https://puu.sh/Ivdm7.jpg

**Comment by Sebola3461** [comment]
when you returned to the site, were you logged in or not?

**Comment by Sebola3461** [comment]
check again that everything is working normally for you now

**Comment by gaston2199** [comment]
yeah it now works 👍
