### ISSUE TITLE
Filter for request-cache on server is needed to defend JSON manually inputs

### ISSUE THREAD

**Issue by arken1015** [Sebola3461/osumodweb#8]
![image](https://user-images.githubusercontent.com/15097929/145677028-595b709c-4e3f-40be-885c-ea61f0ee2a78.png)

Currently, the website shows only user's pending/WIP mapsets. It seems okay IF the user has no bad thinking. But since there's some tries to send wrong requests by editing Session Storage, the server should filter the input value so not good JSON would be rejected.

Tried cases
1. Request my '**RANKED**' mapset < This is fixed already
2. Request '**other user**' 's mapset(Regardless of status) < **Not fixed**
3. Request on queue that doesn't exist < 404 return so okay
4. Request **graveyarded** mapset < It works. But this can be possible case with right using
5. Request **qualified** mapset < It works. But this can be possible.
6. Request **Loved** mapset < It works. And this is not good using

https://osu.ppy.sh/docs/index.html#beatmapsetcompact-rank-status

Here's the official reference for this. The only allowed value would be -2 , -1 and 0

**Comment by Sebola3461** [comment]
Ill implement this in the next build, thx.

**Comment by Sebola3461** [comment]
its fixed now.
